// <auto-generated />
using System;
using AlgorithmicLanguagesPracticProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlgorithmicLanguagesPracticProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Один з найкращих фільмів!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MediaId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Сюжет тримає в напрузі до кінця.",
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            MediaId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Візуал і музика просто чудові.",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            MediaId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Дуже теплий і мотиваційний мультфільм.",
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            MediaId = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Фантастичний фільм про дослідження космосу.",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 2014,
                            StudioId = 1,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Науково-фантастичний трилер про сни.",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            StudioId = 2,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Епічна фантастична історія про боротьбу за Арракіс.",
                            Rating = 8.0,
                            ReleaseYear = 2021,
                            StudioId = 1,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Анімаційний фільм про сенс життя та музику.",
                            Rating = 8.0999999999999996,
                            ReleaseYear = 2020,
                            StudioId = 3,
                            Title = "Soul"
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Universal"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Warner Bros"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "Pixar"
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@local",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user1@local",
                            PasswordHash = "5gbjiw2MGbJM8O44CBgxYup81j/3kS27IrXoAyhrREY=",
                            Role = "User",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user2@local",
                            PasswordHash = "k36NX7tIvUlJU2zWW401xCa4DS+DDFwwjizexCKuIkQ=",
                            Role = "User",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Comment", b =>
                {
                    b.HasOne("AlgorithmicLanguagesPracticProject.Models.Entities.Media", null)
                        .WithMany("Comments")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Media", b =>
                {
                    b.HasOne("AlgorithmicLanguagesPracticProject.Models.Entities.Studio", "Studio")
                        .WithMany("Medias")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Media", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Studio", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
