// <auto-generated />
using System;
using AlgorithmicLanguagesPracticProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlgorithmicLanguagesPracticProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324190232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Один з найкращих фільмів!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MediaId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Фантастичний фільм про дослідження космосу.",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 2014,
                            StudioId = 1,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Науково-фантастичний трилер про сни.",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            StudioId = 2,
                            Title = "Inception"
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Universal"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Warner Bros"
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@local",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Comment", b =>
                {
                    b.HasOne("AlgorithmicLanguagesPracticProject.Models.Entities.Media", null)
                        .WithMany("Comments")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Media", b =>
                {
                    b.HasOne("AlgorithmicLanguagesPracticProject.Models.Entities.Studio", "Studio")
                        .WithMany("Medias")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Media", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AlgorithmicLanguagesPracticProject.Models.Entities.Studio", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
